name: Build and Publish for coursework

on:
  push:
    branches: [coursework]

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: self-hosted
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore /p:TreatWarningsAsErrors=false

    - name: Test
      run: dotnet test ${{ env.SOLUTION_FILE_PATH }} --verbosity normal /p:TreatWarningsAsErrors=false
      
    - name: Publish application
      run: dotnet publish --configuration Release --output ./publish --no-build /p:TreatWarningsAsErrors=false
      
